---
- hosts: webserver
  vars:
    - create_user_file: yes
    - user: ec2-user
  tasks:
    - name: create file for user
      file:
        path: /home/{{ user }}/myfile
        state: touch
      when: create_user_file